# .streamlit/config.toml

[theme]
# Sleek Dark Mode Theme v1
primaryColor="#007BFF"             # A standard, professional blue (Bootstrap Blue)
backgroundColor="#0F1116"         # Slightly adjusted very dark background
secondaryBackgroundColor="#1E2128" # Slightly adjusted darker secondary background
textColor="#E0E0E0"               # Slightly off-white text for potentially softer contrast
font="sans serif"                 # Standard sans-serif font (safe choice)

# You can experiment with other primary colors too:
# primaryColor="#546E7A" # Blue-Grey
# primaryColor="#4A90E2" # Another professional blue shade
# primaryColor="#008080" # Darker Teal

# You could also try a different base font if preferred, though options are limited without CSS:
# font="serif"
# font="monospace"


# --- Runner, Server, Logger settings remain the same ---
[runner]
fastReruns = true

[server]
# port = 8501
# headless = false

[logger]
level = "info"

# --- Original Dark Mode Theme (for reference) ---
# [theme]
# primaryColor="#00A0B0" # A vibrant teal for primary elements
# backgroundColor="#0E1117" # Very dark (almost black) for the main background
# secondaryBackgroundColor="#161A25" # Slightly lighter dark for element backgrounds
# textColor="#FAFAFA" # Light text for readability on dark backgrounds
# font="sans serif" # Standard sans-serif font
